services:
  audiolm-env:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
      - "6006:6006"
    tty: true
    command: jupyter-lab . --allow-root --ip 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]